### ISSUE TITLE
Add a section that contains the most common pitfalls and how to avoid them

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#221]
**Problem Description:**

There are common things people should avoid doing

**Suggested Solution:**

I think if we had a new page for that we could recommend _everyone_ read that page regardless of how you're using glamorous. Here are some things that should be on that page:

- [ ] Remember to forward the `className` if you're wrapping a custom component in `glamorous` https://github.com/paypal/glamorous/issues/112
- [ ] Never use object spread (or Object.assign) when merging styles, use an array instead (object spread is shallow, so pseudo classes/etc. wont merge). Giving an array will make glamorous forward them all to glamor which will merge them. https://github.com/paypal/glamorous/issues/142
- [ ] If you're using `glamor.css` and passing it to `className`, make sure to call `toString()` on it https://github.com/paypal/glamorous/issues/140
- [ ] Describe order of priority with regard to `...styles` -> `className` -> `props as css` -> `css prop` https://github.com/paypal/glamorous/issues/195
- [ ] Avoid using shorthands in combination with longhand forms due to object key order not being deterministic so it's unclear which will override the other. In generally it's really just best to avoid shorthand if you want to enable composability of styles at all.

I'm sure there are other things that should go on that kind of page. Ideas welcome.

**Comment by paulmolluzzo** [comment]
@tkh44 That's a great tip! I'm really interested in seeing flame graphs if you want to share. (Your benchmarks on `emotion` are 💯. Thank you!)

`restyles` looks awesome. We should have that in Integrations for sure!

**Comment by tkh44** [comment]
Here is a gif explaining this concept better than anything I could write.

![quickdigitalanura-size_restricted](https://user-images.githubusercontent.com/662750/28141107-6c3927d4-6718-11e7-8b7b-630f60e9fecb.gif)

Here you can see that one glamorous component is under 1ms so not bad. The problem is when you nest multiple glamorous elements as you can see. There were ~30 items in that section so it took 30+ms to render that small section of the tree.

**Comment by guidobouman** [comment]
@tkh44 Is that in a production build? Because develop & production are different when comparing performance.

**Comment by tkh44** [comment]
This was in production @guidobouman. I resolved the issue by creating https://github.com/emotion-js/emotion. The fundamental problem with glamorous is that it invalidates glamor's WeakMap caching implementation resulting in complete style recalculation on ever render.

**Comment by paulmolluzzo** [comment]
@tkh44 would you mind pointing out where that occurs? I'd be interested in learning more about that specifically. Thanks!

**Comment by kentcdodds** [comment]
Wait... What? I was unaware of this. I'd like to know how that happens and how it can be fixed....... If it weren't you Kye, I'd say you were mistaken...

**Comment by tkh44** [comment]
When the glamor class name is calculated here https://github.com/paypal/glamorous/blob/73cbc5f6a92aa003387a073449f8b3136804ba8c/src/get-glamor-classname.js#L75 it returns a new array every time.

This causes a cache miss in Glamor's WeakMap cache.

https://github.com/threepointone/glamor/blob/master/docs/weakmaps.md#so-how-can-we-use-it-with-glamor

I don't know if there is anything you can do. The same symptom exists in most css-in-js libraries that have a component wrapper, including emotion. I won't pretend to know all the details that go into the performance differences between emotion and glamorous when using dynamic values. The obvious, hand-wavey guess is that emotion is just doing less work to calculate the same style.

I also want to apologize for the tone of my original comment. The statement should have had more clarification.

**Comment by kentcdodds** [comment]
No worries on the tone. I didn't take it any more than a clarification. I'm just surprised because I was under the impression that we were taking advantage of the cache. I think I understand what's going on and I suppose there's some optimization we could do to ensure that if the styles are the same we use the same array. Thanks for sharing this insight!

I'm not going to personally pursue this any further because I have other more pressing matters WRT performance in my app, but if someone else wants to improve things that'd be pretty great :+1:

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see [the glamorous README](https://github.com/paypal/glamorous) for more information.
